[package]
name = "feg-infer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true
description = "Inference implementation and FEEC/GMRF adapters for FEEC-GMRF"

[features]
default = []
external-solver-tests = []

[dependencies]
feg-core = { path = "../feg-core" }
formoniq = { path = "../../feec/crates/formoniq" }
manifold = { path = "../../feec/crates/manifold" }
common = { path = "../../feec/crates/common" }
exterior = { path = "../../feec/crates/exterior" }
ddf = { path = "../../feec/crates/ddf" }
gmrf-core = { path = "../../gmrf-rs" }
rand = "0.8"
faer = { workspace = true }
rand_distr = { workspace = true }
libm = "0.2"

[dev-dependencies]
feg-gp = { path = "../feg-gp" }

[[bench]]
name = "variance_estimators"
harness = false
